exports.CREATE_DATABASE_SQL = `

  CREATE TABLE IF NOT EXISTS LOGO_COMMISSION
  (
    ID               UUID PRIMARY KEY,
    CONTRACT_ADDRESS VARCHAR(100),
    LOGO_DESCRIPTION VARCHAR(500),
    ACTIVE           BOOLEAN   NOT NULL,
    CREATION_TIME    TIMESTAMP NOT NULL,
    TRANSACTION_HASH VARCHAR(150)
  );

  CREATE TABLE IF NOT EXISTS LOGO_PROPOSAL
  (
    ID                    UUID PRIMARY KEY,
    LOGO_COMMISSION_ID    UUID         NOT NULL REFERENCES LOGO_COMMISSION (ID),
    LOGO_COMMENT VARCHAR(100),
    PICTURE_ORIGINAL_NAME VARCHAR(200) NOT NULL,
    PICTURE_NAME VARCHAR(200) NOT NULL,
    PICTURE_MIME_TYPE VARCHAR(100) NOT NULL,
    PICTURE_SIZE NUMERIC NOT NULL
  );
`;